# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
#    command: uvicorn main:app --host 0.0.0.0
    volumes:
      - .:/app
    environment:
      - SERVER_GS4U_URL=${SERVER_GS4U_URL}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - CHAT_ID=${CHAT_ID}
      - DB_FILE_PATH=/app/server_players.db
    logging:
      driver: "json-file"
      options:
        max-file: "5"   # количество файлов
        max-size: "10m" # размер файла лога
    restart: unless-stopped

